# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(resolve:JWT_TTL)%'

    api_platform:
        check_path: /api/login_check
        username_path: security.credentials.username
        password_path: security.credentials.password