#vich_uploader:
#    db_driver: orm

vich_uploader:
  db_driver: orm
  mappings:
    profile_pictures:
      uri_prefix: /profile_pictures
      upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'

    #      namer: Vich\UploaderBundle\Naming\OrignameNamer
#      inject_on_load: false
#      delete_on_update: true
#      delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
