# config/routes/sonata.yaml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin2

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin2

#admin_app_unit:
#    resource: App\Admin2\UnitAdmin