#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
api_login_check:
    path: /api/login_check

api_sale_list:
    path: /api/sale/list
    methods: GET
    defaults: { _controller: App\Controller\Api\SaleController::list }

api_sale_show:
    path: /api/sale/show/{id}
    methods: GET
    defaults: { _controller: App\Controller\Api\SaleController::show }

api_sale_create:
    path: /api/sale/create
    methods: POST
    defaults: { _controller: App\Controller\Api\SaleController::create }

api_sale_update:
    path: /api/sale/update/{id}
    methods: PUT
    defaults: { _controller: App\Controller\Api\SaleController::update }

api_sale_delete:
    path: /api/sale/delete/{id}
    methods: DELETE
    defaults: { _controller: App\Controller\Api\SaleController::delete }

api_sale_approve:
    path: /api/sale/approve/{id}
    methods: PUT
    defaults: { _controller: App\Controller\Api\SaleController::approve }

# Import routes from SaleController
#sale_api:
#    resource: '@App/Controller/SaleController.php'
#    type: annotation

admin:
    path: /admin/dashboard
    controller: App\Controller\DashboardController::index

#security:
#    path: /security
#    controller: App\Controller\SecurityController::index

#register:
#    path: /register
#    controller: App\Controller\SecurityController::register

user:
    path: /admin/user
    controller: App\Controller\UserController::index

showUser:
    path: /admin/user
    controller: App\Controller\UserController::show

addUser:
    path: /admin/user/add
    controller: App\Controller\UserController::add

editUser:
    path: /admin/user/edit/{id}
    controller: App\Controller\UserController::edit

deleteUser:
    path: /admin/user/delete/{id}
    controller: App\Controller\UserController::delete

login:
    path: /admin/login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

approve_sale:
    path: '/api/sale/approve/{id}'
    controller: 'App\Controller\Api\SaleController::approve'

# config/routes.yaml
app.swagger_ui:
    path: /admin/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# config/routes.yaml
app.swagger:
    path: /admin/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# config/routes.yaml
#api:
#    resource: ../../src/Controller/Api/
#    type: annotation

